# Python Data Science Handbook

##  Useful shortcuts to know
1. `control + a`-> moves cursor to beginning of the line
2. `control + e` -> moves cursor to the end of the line
3. `control + f` - > (f like in forward) moves cursor one char ahead
4. `control + b` -> (b like in back) moves cursor one character backwards



In [27]:
def square(x):
    """square a number"""
    return x ** 2

for N in range(1, 4):
    print(f"{N} squared is {square(N)}")


1 squared is 1
2 squared is 4
3 squared is 9


## IPython Magic Commands
1. `run <filename>` executes file mentioned in command
2. ` %timeit <function>` returns time needed for execution of mentioned function <br> If you want to measure time of execution of multiline code, just add second % sign, as in `%%timeit`
3. `%magic` returns list of available magic functions


## Input and Output history
IPython enables accessing inputted and outputted things <br> By using `In` we can access list containing every line of code of the file, where every list item is dedicated to each line <br> `Out` works identically, it outputs list of outputs for each line <br>
We can access outputed value of specific cell by using `Out[<cell_num>]`, however it is important to insert correct cell number, otherwise we will receive `KeyError Exception`
To print last outputted value, we can simply use `print(_)`



In [28]:
import math
math.sin(2)


0.9092974268256817

In [29]:
print(_)

0.9092974268256817


In [30]:
# Out[1]

## Shell Commands
1. `echo <sth>` <br>
Command used for printing some content, working just like Python `print()`
2.  `pwd` <br>
Command used for printing working directory - our present place of activity
3.  `ls` <br>
Command printing list of elements present in working directory
4.  `cd` <br>
Command used for changing directory. We can specify how we want to move, we can move upwards or downards the path, for example with `cd ..` we will move to the father-folder
5.  `mkdir <name>` <br>
Command for creating new directory with name specified by us
6.  `mv <path/file>` <br>
Command enabling moving file specified by us to specified in path place
*Example* <br>
To move file *text.txt* to folder *sample* all we need to do is to type `mv -v text.txt ./sample`. The second component we type is the destination we want to move our file 90
## Input and Output history
IPython enables accessing inputted and outputted things <br> By using `In` we can access list containing every line of code of the file, where every list item is dedicated to each line <br> `Out` works identically, it outputs list of outputs for each line <br>
We can access outputed value of specific cell by using `Out[<cell_num>]`, however it is important to insert correct cell number, otherwise we will receive `KeyError Exception`
To print last outputted value, we can simply use `print(_)`



## Shell commands in IPython
IPython enables calling shell functions directly in Python cells. We can acheive it by simply adding ! before the command, as shown bellow. Better yet, we can even store the command's output in variables (shown below as well).

In [31]:
content = !ls
print(type(content))

<class 'IPython.utils.text.SList'>


## Shell commands in IPython cont.
We can also pass Python variables to shell commands. It works as follows:


In [32]:
message = "Hello world"
!echo {message}

Hello world


We cannot however execute !cd command and in fact change the working directory. It is because when executing in IPython cells, shell comands are not executed in shell itself, but in subshelf. However we can change the working directory with use of `%cd` magic command or even simpler, by calling just `cd` <br>
### Useful `cd` add-ons:
1. `cd ..` move up one directory level
2. `cd ~` change to the home directory
3. `cd -` switch to the previous directory
4. `cd /` change to the root directory

In [33]:
# cd -

## Errors and Debugging
### Errors
IPython enables 3 modes of controlling exceptions. We can specify it by calling `xmode <mode>`, where mode can be:
1. `xmode Context` default exception handling procedure
2. `xmode Plain` shorter version, we do not receive as much info as with `context` mode on
3. `xmode Verbose` the most advanced mode, where we achieve all of the `context` mode information + info about arguments passed to the functions that were called. The downside of this mode is that, the text message can get enormously long when code is more complex

In [34]:
%xmode Verbose

Exception reporting mode: Verbose


### Debugging
IPython contains very useful command `%debug`. With its use, we can debug our function, step by step. It generates interface, where we can type commands such as, `print(var)` to get the value of variable `var`. We can also type `up` to move up one level or `down`. To exit interface we simply type `quit`. If we want to turn debugger automaticly, we can specify it in command `pdb on` <br>
Other useful commands to use when iteracting with debugger:
1. `list` show the current location in the file
2.  `help` show list of commands
3.  `quit` quits the debugger
4. `continue` quits debugger, continues the program
5. `next` go to the next step of the program
6.  `<enter>` repeats the previous command
7.  `print()` prints value
8.  `step` step into subroutine
9.  `return` return out of subroutine

In [35]:
def func(a):
    b = a - 1
    return a/b
func(2)

2.0

In [36]:
%debug

    [... skipping 1 hidden frame(s)]
  /var/folders/28/q69_byq539765spkxlp_hpx80000gn/T/ipykernel_32744/2886015032.py(1)<module>()
----> 1 get_ipython().run_line_magic('cd', '-')
  /Users/m1niu/PyCharmMiscProject/hands-on-data-science/.venv/lib/python3.14/site-packages/IPython/core/interactiveshell.py(2532)run_line_magic()
   2530                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2531             with self.builtin_trap:
-> 2532                 result = fn(*args, **kwargs)
   2533 
   2534             # The code below prevents the output from being displayed
> /Users/m1niu/PyCharmMiscProject/hands-on-data-science/.venv/lib/python3.14/site-packages/IPython/core/magics/osm.py(389)cd()
    387                 ps = self.shell.user_ns['_dh'][-2]
    388             except IndexError as e:
--> 389                 raise UsageError('%cd -: No previous directory to change to.') from e
    390         # jump to bookmark if needed
    391         else:

--KeyboardInterrupt-

## Profiling and Timing Code
While creating code, the first thing we want to achieve is to make it work as we wish. Before we achieve it, there is no point in optimizing it, by doing so we could only make things worse. However once we have working code it is good thing to measure the execution time of it and maybe finding bottleneck in it. <br>
IPython contains several useful method in this field
<br> `%time` time the execution of single statement
<br> `%timeit` time repeated execution of single statement for more accuracy
<br> `%prun` run the code with the profiler
<br> `%lprun`  run code with the line-by-line profiler
<br> `%memit` measure the memory use of a single statement
<br> `%mprun` run code with line-by-line memory profiler

## Two's complement numbers
Two's complement number is a form of presenting integers in binary system. Logic of binary system is as follows - we present number as if it was made as a sum of different powers of number 2. Starting from the edge we have 2^0, which is 1. Then every following number have increased by 1 power: *2^1, 2^2,2^3 ...*. In such representation number 5 is presented as "101", because we have `1*2^2+0*2^1+1*2^0` <br>
When we want to represent negative numbers as well, we need to add small change,
 being that the first digit states if we have negative or positive number  (0 for
  positive, 1 for negative). Writing negative number -x is equal with writing (x-1) bitwise, with all the bits complemented (swapped from 0 to 1 and from 1 to 0). This way writing -10 bitwise is equal to writing complement(9)=complement("00001001")=11110110"


## Bitwise operators
Python contains several bitwise operators:
1. `x << y` returns x with the bits shifted to the left by y place (new bits on the right-hand are zeros). It is equal to multiplying x by 2**y
5 << 2
"101" = "10100" = 20 = 5 * (2^2)
2. `x >> y` returns x with bits shifted to the right by y place. This is the same as floor division of x by 2**y
3. `x&y` does a bitwise *and*. Each bit of the output is 1 if the corresponding bit of x AND y is 1, otherwise it is 0.
4.  `x|y` each bit of the output is 0 if the corresponding bit of x AND y is 0, otherwise ut us 1.
5. `~x` returns the complement of x - the number you get by switching 1 for 0 and each 0 for a 1. Tis is the same as -x-1
6. `x^y` does a bitwise exclusive or. Each bit of the output is the same as the corresponding bit in x if that bit in y is 0, and it's he complement of the bit in x if that bit in y is 1.
Infinite series of 1 bits is a negative number.

In [37]:
print(~20)

-21


## Line-by-line profiling with `%lprun`
Sometimes more useful is to profile each line of our function and get insights of it. We can do it with use of `%lprun`, however first we need to install the package `line_profiler` <br> `pip install line_profiler` and then we need to load it `%load_ext line_profiler` and we are ready to profile any of our functions line-by-line. <br> *Example* <br> `%lprun -f sum_of_lists(5000)` <br> the result of the function is report for every line of function. Time is measured in microseconds. Knowlage of detailed time consumption of each line is crucial, as it enables us to achieve better performance by changing some of the most time consuming code.

## Profiling memory use with `%memit` and `%mprun`
Anothe aspect of profiling is seeing how much memory an operation use. We can measure it with `memory_profiler` packagce. First we have to install it and load it. <br> `pip install memory_profiler`. <br> Next we load it `%load_ext memory_profiler`. Now we can get useful insight of our function memory consumption by simply calling `%memit sum_of_lists(100000)` <br> However to use `%mprun` we need to first create simple module containg our function, otherwise it wont work. `%% file mprun_demo.py`, then all we need to do is import our function from module `from mprun_demo import sum_of_lists` and call the `%mprun` --> `%mprun -f sum_of_lists sum_of_lists(1000000)`


# NumPy


In [ ]:
!pip install numpy

In [38]:
import numpy as np

## NumPy array
NumPy array is object similar to the Python list, however there are some differences between them. Python list can contain heterogeneous datatypes, but NumPy array can only contain same data type object. Python list is more flexible however also need much more resources, as every object have to contain additional informations about it, such as its type. NumPy array however, similar to C array can contain only homogenous objects.

In [ ]:
np.array([1,2,3,4], dtype=np.float32)

In [ ]:
np.array([1,2,3])

NumPy arrays also are multidimensional --> array can contain another array or arrays, while Python list is strictly one dimensional

In [ ]:
np.array([[range(i,i+3) for i in range(1,4)]])

## Creating arrays from scratch
While working with larger arrays, it is more efficient to create arrays from scratch using routing build into Numpy

In [ ]:
np.zeros(10, dtype=int)

Creates array containing only 0's

In [ ]:
np.ones((3,5), dtype=int)

Creates array made of 1's only, with specified dimensions

In [ ]:
np.full((3,5), 3.14)

Creates array made of only of specified value with specified dimensions of array.

In [ ]:
np.arange(0,20,2)

Creates array filled with numbers from 0C

In [ ]:
np.linspace(0,1,5)

Creates array with 5 numbers, evenly spaced from range 0 to 1

In [39]:
np.random.random((3,3))

array([[0.21695415, 0.64091361, 0.3581674 ],
       [0.9744497 , 0.49245001, 0.33644497],
       [0.38843581, 0.38183585, 0.32975326]])

In [ ]:
np.random.normal(0,1,(3,3))


Creates 3x3 array with values of normal distribution wth 0 as mean and 1 as standard deviation

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Creates identity matrix of specified size

In [41]:
np.random.randint(0,10,(3,3))

array([[3, 5, 8],
       [5, 5, 2],
       [9, 1, 0]])

Creates array filled with pseudorandom integers from interval 0 to 10

In [42]:
np.empty(3)

array([0.e+000, 5.e-324, 1.e-323])

## NumPy Arrays