# NumPy arrays

## NumPy arrays attributes
NumPy arrays attributes worth knowing:
1. `array.ndim` returns information about number of dimensions of array
2.  `array.size` returns number of elements contained inside array
3.  `array.shape` returns shape of array, for example (3,4,5) --> 3-dimensional array with 4 rows and 5 columns each
4. `array.dtype` returns information about data type of elements

In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed=1701)

In [3]:
x1 = rng.integers(10, size=6)
x2 = rng.integers(low=1, high=10, size=(3,4))
x3 = rng.integers(10, size=(3,4,5))
#10 is the upper bound of the range from which the numbers are drawn
#creates 3-dimensional array with 4 rows each and 5 columns each

In [4]:
x3.size

60

In [5]:
x1.ndim

1

In [6]:
x1.shape

(6,)

In [7]:
x1.size

6

In [8]:
x1.dtype

dtype('int64')

## Arrays indexing
Accessing arrays elements is identical as with Python lists. However, when working with multidimensional arrays we can simply access values as follows. <br>
`array[2,2]` access 3rd element of 3rd row <br>
*Note* Because numpy arrays can contain only values of same data type, when we try to add value of different data type it will result in casting this value to type of the array values. For example adding float to integer array will result in truncating float to its integer part. Adding integer to float array will change the integer into float.

In [9]:
x3[2][::-1]

array([[3, 2, 7, 4, 7],
       [0, 3, 0, 0, 2],
       [9, 2, 2, 4, 0],
       [2, 9, 4, 3, 9]])

## Array slicing
Arrays can be sliced same way as Python lists. Slicing is proceeded as follows `array[start:stop:step]`. Special case is setting negative value for step. In that case we will present array in reversed order (if step is -1).

## Accessing array rows and columns

In [10]:
x2[:,0]

array([4, 4, 1])

## Subarrays as No-Copy Views
NumPy array slices are returned as view objects, rather than copies of the array data

In [11]:
x2_sub = x2[:2,:2]

In [12]:
x2_sub[0,0] = 0

Unlike list slices, NumPy array slices are views, not separate objects. This way, modifying slice of array, will change modify the array itself!

In [13]:
x2[:2,:2]

array([[0, 2],
       [4, 1]])

## Creating copy of array
Sometimes it is useful to create copy of array, rather than working with its view. <br> We can achieve it by simply typing `array2 = array.copy()`

## Reshaping the array
Arrays can be reshaped into any shape we want to. To achieve it we use following syntax: `array.reshape((shape))` <br> **Note:** The only thing limiting us, is that the new shape has to be equal to the size of the array. Array containing 10 elements (size = 10) can only be take shape, which product of multiplication is equal to size, meaning 10 = 2 * 5, 10 = 10 * 1. Otherwise, we will recieve error

In [14]:
x = np.linspace(1,100,10)

In [15]:
x.reshape(2,5)

array([[  1.,  12.,  23.,  34.,  45.],
       [ 56.,  67.,  78.,  89., 100.]])

In [16]:
print(x.reshape(10,1))

[[  1.]
 [ 12.]
 [ 23.]
 [ 34.]
 [ 45.]
 [ 56.]
 [ 67.]
 [ 78.]
 [ 89.]
 [100.]]


In [17]:
x[np.newaxis,:]

array([[  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]])

In [18]:
x[:, np.newaxis]

array([[  1.],
       [ 12.],
       [ 23.],
       [ 34.],
       [ 45.],
       [ 56.],
       [ 67.],
       [ 78.],
       [ 89.],
       [100.]])

If we simply want to reshape array as row vector or column vector, we can use `np.newaxis`. It works like this: `x.reshape[np.newaxis,:]` for row vector or `x.reshape[:,np.reshape]`

## Array Concatenation and Splitting
NumPy enables concatenating multiple arrays into one, as well as splitting one array into multiple arrays.


In [19]:
x = np.arange(3)
y = np.arange(3)
np.concatenate([x,y])

array([0, 1, 2, 0, 1, 2])

In [20]:
z = np.array([[1,2,3],[4,5,6]])

In [21]:
z

array([[1, 2, 3],
       [4, 5, 6]])

Similarly to adding singe arrays, we can also concatinate multidimensional ones

In [22]:
np.concatenate([z,z], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Inside our syntax we can also specify along, which axis we want to concatenate our arrays. Concatenating is essentially like gluing together two arrays. If we want to do it along 1 axis (columns), the second array will appear alongside the first one. If we specify axis to be 0 (rows), the second array will appear below the first one

When we are working with arrays of mixed dimensions, it will be easier to use `np.vstack` --> vertical stack or `np.hstack` --> horizontal stack. For arrays of more than 2 dimensions there is `np.dstack` function

In [23]:
np.vstack([x,z])


array([[0, 1, 2],
       [1, 2, 3],
       [4, 5, 6]])

In [24]:
x

array([0, 1, 2])

In [25]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
print(z)

[[1 2 3]
 [4 5 6]]
